import React from 'react';
import { ColumnChart } from '../common/ColumnChart.js';

export function AboutPage() {
  const factors = [
    { name: 'Material Compatibility', weight: 35, desc: 'Evaluates direct re-usability, chemical suitability, and cross-industry substitution rules.' },
    { name: 'Transport Feasibility', weight: 25, desc: 'Calculates physical road transit distance between industrial clusters and logistic viable radii.' },
    { name: 'Quantity Fit', weight: 15, desc: 'Matches batch supply volumes against receiver monthly demand capacity without bottlenecking.' },
    { name: 'Quality Match', weight: 15, desc: 'Cross-references required input purity against generated by-product quality grade tiers.' },
    { name: 'Availability Frequency', weight: 10, desc: 'Aligns generation schedule (continuous, weekly, monthly) with manufacturing intake cycles.' },
  ];

  return (
    <div>
      <div className="page-header">
        <div className="page-header-container">
          <div>
            <p className="label-caps">Platform Architecture</p>
            <h1 className="page-header-title">About Waste 2 Worth</h1>
            <p className="page-header-desc">
              An industrial waste-exchange layer that turns disposal liabilities into recoverable secondary raw materials through deterministic mathematical matching.
            </p>
          </div>
        </div>
      </div>

      <div
        style={{
          maxWidth: '1200px',
          margin: '0 auto',
          padding: '2rem 1.5rem',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
          gap: '2rem',
        }}
      >
        {/* Left Column: Mission & Scoring Model */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <div className="card-soft" style={{ padding: '1.5rem' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600 }}>The Industrial Circularity Challenge</h2>
            <p style={{ marginTop: '0.5rem', fontSize: '0.875rem', lineHeight: 1.6, color: 'var(--muted-foreground)' }}>
              Indian industrial clusters generate enormous, highly consistent by-product streams — polymer regrind, steel slag, foundry sand, spent solvents, and agricultural biomass. Most is routinely landfilled or downcycled because manufacturing plants that could utilize it as virgin raw material substitutes never know it exists.
            </p>
            <p style={{ marginTop: '0.75rem', fontSize: '0.875rem', lineHeight: 1.6, color: 'var(--muted-foreground)' }}>
              Waste 2 Worth closes this information gap by registering verified industrial streams alongside manufacturer raw material requirements and scoring every viable pairing with 100% explainability.
            </p>
          </div>

          <div className="card-soft" style={{ padding: '1.5rem' }}>
            <p className="label-caps" style={{ color: 'var(--navy)' }}>Scoring Model — 5-Factor Weighted Formulation</p>
            <div style={{ marginTop: '1rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {factors.map((f) => (
                <div
                  key={f.name}
                  style={{
                    padding: '0.75rem',
                    backgroundColor: 'var(--surface-2)',
                    borderRadius: 'var(--radius-md)',
                    border: '1px solid var(--border)',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span style={{ fontWeight: 600, fontSize: '0.8125rem', color: 'var(--navy)' }}>{f.name}</span>
                    <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, fontSize: '0.8125rem', color: 'var(--brand-blue)' }}>
                      {f.weight}%
                    </span>
                  </div>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted-foreground)', marginTop: '0.25rem' }}>
                    {f.desc}
                  </p>
                </div>
              ))}
            </div>

            <div style={{ marginTop: '1rem', borderTop: '1px solid var(--border)', paddingTop: '0.75rem', fontSize: '0.75rem', color: 'var(--muted-foreground)' }}>
              <strong>Pre-Filters:</strong> Hazardous streams with unlicensed receivers are excluded at Gate 1. Incompatible materials are excluded at Gate 2. Totals &lt; 40 are excluded from results.
            </div>
          </div>
        </div>

        {/* Right Column: Column Chart Visualization */}
        <div className="card-soft" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column' }}>
          <p className="label-caps">Circular Impact Projection</p>
          <h2 style={{ fontSize: '1.125rem', fontWeight: 600, marginTop: '0.25rem' }}>
            Waste Diverted by Stream (Tonnes)
          </h2>
          <p style={{ fontSize: '0.75rem', color: 'var(--muted-foreground)', marginTop: '0.25rem' }}>
            Modeled outcomes across key manufacturing sectors in the active prototype registry.
          </p>

          <div style={{ marginTop: '1.5rem', flex: 1 }}>
            <ColumnChart metric="diverted" height={280} />
          </div>

          <div style={{ marginTop: '1.5rem', borderTop: '1px solid var(--border)', paddingTop: '1rem', fontSize: '0.75rem', color: 'var(--muted-foreground)', lineHeight: 1.5 }}>
            Every tonne of industrial by-product repurposed directly offsets virgin extraction energy, eliminates landfill transport tipping fees, and lowers Scope 3 supply-chain carbon intensity.
          </div>
        </div>
      </div>
    </div>
  );
}
